### ISSUE TITLE
the battle between chase and the kernel is broken

### ISSUE THREAD

**Issue by vlad-a-c** [munawarb/Three-D-Velocity#107]
after the little conversation between hase and the kernel after the destruction of the airbase, once the cut scene is done the hole sound breaks and it comes back after chase dies, so i can't really do anything in the battle.

**Comment by munawarb** [comment]
Hi @vlad-a-c,
Thanks for reporting this. Do you mean that the fight sounds seem to be muted? It's a consequence of the switch to XAudio2 because those sounds are using the same output device as the rest of the game now that I'm thinking about it. This is what I can think of off the top of my head at the moment.

**Comment by vlad-a-c** [comment]
yes. everything mutes until the end of the fight when i get defeated.
