### ISSUE TITLE
Multiple problems using Phantom Hawk joystick

### ISSUE THREAD

**Issue by davidkreynolds** [munawarb/Three-D-Velocity#117]
Using a Phantom Hawk Joystick.
1.Various keys on the joystick act like escape key, so you can't program them to game actions.
2.There would appear to be no way to open the throttle when using a joystick.

**Comment by munawarb** [comment]
Hi,
Can you describe the joystick to me? Does it have anything that could control the throttle?

**Comment by davidkreynolds** [comment]
Hi Munawar,

 

The throttle issue was my fault, and I’ve now discovered how to operate the throttle correctly.

However, in training mode, when I pull back the stick to climb, I hear a lot of numbers spoken, and eventually I crash.

It is possible that I’m not pulling it back enough or pulling it back too much.

It is difficult to tell, but using the joystick, I’ve never completed training mode.

If you need me to test or try anything, I’m very happy to do so.

This is a great game,

 

David.

**Comment by blindpilot** [comment]
Hi at you Dave, from Ron Kolesar, AKA The Blind Pilot, and also grateful on where I might be able to pick it online or here in the states or online.
I’d be deeply grateful if you could describe the Phantom Hawk Joystick and throttle two stick controller that you have.
How many buttons does it have for starters?
From what I remember, TDV will work with a minimum of twelve buttons, but I’d like to see something with at least say twenty buttons on the unit.
That way we wouldn’t have to constantly switch back and forth not only with the TDV flight simulator features, but with the other hand to ear coordination games where we could get the most out of the joystick and not to constantly switch back and forth between features that only work with the joystick and other features that only works via the keyboard.
When Munawar original proposed the TDV hand to ear military flight simulator to us back in 2010, we had a two stick joystick and more importantly in the days of the 32 bit processor, it supported the built in force feedback feature of TDV.
Sadly, no other hand to ear product has Munawar’s force feedback feature written into their hand to ear products.
I have access to the old Pipe version two, better known as blast chamber which would be awesome if it had not only force feedback support but also shock feedback as well.
I’ve asked Munawar this several times with no success.
But there is a roomer that TDV will also support a USB set of petals to bring it even closer to the real world.
It would be awesome if that roomer could be settle to proven fact, once and for all to bring flying and gaming closer to the real world as well.
I have been writing to Microsoft about their new project, still due to be released on October 13th, of 2020, the new Microsoft Flight Simulator 2020 project.
It is all over the internet and also all over face book.
I’d love to be able to fly once again in the FSX project.
But I’d also love to play the hand to ear games that I still have on my pc and work in the world of win 10 with a 64 bit processor and also have joystick support written into the games as well.
Now to answer your question, It take a lot of trial and error and a little bit of luck to learn how must and how little throttle to use for a seccful takeoff and landing.
I too was in your shoes when we stress tested TVD in the good old days of it’s beginning.
I had a thrustmaster two stick joystick that support force feedback in those days, and yes it does take a lot of practice to manage the controls.
Sorry, I can’t be of more help.

You can reach me at:
kolesar16417@roadrunner.com
Very Thankfully Yours,
Ron Kolesar AKA The Blind Pilot

From: davidkreynolds 
Sent: Thursday, March 19, 2020 18:58
To: munawarb/Three-D-Velocity 
Cc: Subscribed 
Subject: [munawarb/Three-D-Velocity] Multiple problems using Phantom Hawk joystick (#117)

Using a Phantom Hawk Joystick.
1.Various keys on the joystick act like escape key, so you can't program them to game actions.
2.There would appear to be no way to open the throttle when using a joystick.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

In the good old days of Morse code Shorthand, 73's AKA Best Regards and or Best Whishes,From
Ron Kolesar
Volunteer Certified Licensed Emergency Communications Station
And 
Volunteer Certified Licensed Ham Radio Station
With the Call Sign of KR3DOG

**Comment by munawarb** [comment]
Hi @davidkreynolds,
Yes, you're most likely pulling it back too far. Have you run through calibration?

**Comment by davidkreynolds** [comment]
Hello Ron,

 

Thanks for writing.

I’ll attempt to describe this joystick to you, then outline the  problems I’m having.

Lets’s start at the bottom.

There are six programable buttons across the bottom.

The throttle control is on the left, and has no spring return, so whereever you put it, it stays.

The main stick has two fire buttons, one at the top and another at the bottom.

The stick moves in all directions, and also rotates.

At the top of the stick, there is a control forming a star with four buttons.

Alongside this, is a small round control which also moves in four directions. There is also a button on its own, so effectively there are 12 programmable controls.

The problem with the throttle is fixed now. I crash when I pull back the stick.

In training mode, I get off the ground fine, but when I try to climb to 10,000 feet, I suddenly crash.

I got this game because it looked really good and promises great potential. I’m sure that I’ll get it to work eventually.

I tried to calibrate the joystick, but having no sight, this proved impossible.

Have you tried Eurofly yet?

I hope that the offering from Microsoft proves accessible, as it is definitely something I’d like to try.

I forgot to mention that my joystick has force feedback, and every time I launch the game, it tells me to install the driver correctly,

 

Very grateful for your message and for any hints,

 

David (Cadet)

**Comment by davidkreynolds** [comment]
Hi,

 

I tried to run the calibration, but it is tricky with a screen reader, as I’m not sure whether the stick is working correctly,

 

David.

**Comment by munawarb** [comment]
Hi @davidkreynolds,
Sorry, I should have clarified. TDV lets you calibrate the joystick in-game. I think if you go to change input devices and then to joystick it should bring up the calibration wizard. I don't remember; been a long time since I've looked at it.

**Comment by munawarb** [comment]
Hi @blindpilot,
I'm also interested to know about this joystick. You can find details here: https://www.amazon.com/SPEEDLINK-PHANTOM-Flightstick-Right-handed-Black/dp/B00M1R7QGG

**Comment by blindpilot** [comment]
Hi back at you Dve.
The unit that I had, had two sticks and around each stick had six buttons around it with I think it had two fire buttons on the stick.
It also had force feedback for the unit.
It also had two caps on the top of each stick.
I think this was a extra button that one could program.
It sounds to me that you might have a bug in the unit that you have.
For taking off and lading, this does take some practice.
I too am looking forward to MS’s new project here in UOctober.
You might want to do a internet search fo roughly Microsoft Flight Simulator 2020 home.
Or Ms FS 2020 home or simply fs 2020 home.
Once in the home page for the new up coming FS 2020 project, you can subscribe to that info and be updated with new info when it’s available.
You also might want to go out to you tube and subscribe to the Microswoft Flight Simulator 2020 you tube page as well.
I like the virble lectures over the text messages that one receives via e-mail.
Please keep me in the loop on getting your unit to work.
I think yes you’ll enjoy this program.
I would love to find for now at least a USB flight yoke and twistable throttle package and hopefully find a package that will support force feedback and for the old blast chamber game also would have shock feedback as well.
I hope my feedback was of some help.
Please stay in touch and I’ll share anything I receive from Microsoft.
Very Thankfully Yours,
Ron Kolesar In the Flight Sim World known as the Blind Pilot and in real life, known as Volunteer Certified Licensed Emergency Communicator Station and Volunteer Certified Licensed Ham Radio Station, both by the call sign of KR3DOG

**Comment by blindpilot** [comment]
Will have to do some research on this stick if and when I get a free minute. SMILES.
This also would be a great question for our leader and original main designer Munawar.
Last I knew, Munawar was swearing by the Thrust master duel stick unit.
But Thrust Master if I remember correctly dropped the force feedback handheld controllers.
Please keep me in the loop on the progress of getting this unit to work not only with TDV but it’s possibilities to work with the Current flight simulator Microsoft Flight Simulator version ten, better known as FSX and the up coming fs 2020 project and with as many hand to ear products as possible.
Ron KR3DOG

**Comment by davidkreynolds** [comment]
Hi Munawar,

When I select the joystick, a lady’s voice warns me that force feedback has been disabled. I then get a message: Joystick configured,

 

David.

**Comment by davidkreynolds** [comment]
Hi Ron,

 

Got a little further. I suspect I know what is going wrong, but not sure how to fix it.

When I pull back on the stick, I hear a clicking which pans from one side to the other. I’m not sure what this means. I get off the ground alright, but when I attempt to go above 10000 feet, all hell breaks loose,

 

Best,

 

David.

**Comment by burakyuksek** [comment]
Hello,
You somehow seem to turn very sharply to one direction.

**Comment by blindpilot** [comment]
Sounds like you might have found a bug in the code.
I say this because I never ever heard a clicking sound.
Many thanks though.
Ron

**Comment by davidkreynolds** [comment]
Ron,

 

You have me interested in FSX now. Is it possible for someone without sight to play it. If so, is there a youtube video of someone doing so,

 

Thanks,

 

David.

**Comment by munawarb** [comment]
Hi @blindpilot and @davidkreynolds,
This isn't a bug. The clicking sound you're hearing is a turning guidance. The click indicates the direction of North, or zero degrees. As you turn to the right, You'll notice the clicking move off to your left to indicate that North is to your left.

What's happening here is that your aircraft is starting to turn without your knowledge. Make sure your throttle stick is centered and not twisted and that your rudder mechanism, if you have one that's not the twistable throttle stick, is centered.

When you first get off the ground, don't pull back all the way on the stick. TDV accounts for the pressure you apply and will react appropriately. So if you pull back too hard, you will stall your aircraft. This is why you're crashing.

**Comment by davidkreynolds** [comment]
Hi Munawar,

 

Yes, that figures. Now I know what’s causing it, I can correct accordingly.

Does the twist mechanism have any effect in the game?

 

David.

**Comment by munawarb** [comment]
Hi @davidkreynolds,
Yes, the twisting is how you control the rudder on your aircraft. I would recommend the training mode so that you can get familiar with how the aircraft works.

**Comment by davidkreynolds** [comment]
Hi,

 

That would explain it. I’m probably twisting as I pull back on the stick.

Now I know how to correct it, it shouldn’t be too much of a problem,

 

David.

**Comment by munawarb** [comment]
Great, let me know if you have any further problems with this, and have fun!
