### ISSUE TITLE
TDV should show proper error message if XAudio2 is missing

### ISSUE THREAD

**Issue by munawarb** [munawarb/Three-D-Velocity#40]
Right now, TDV shows a dialog box and in the error log shows a `NullReferenceException` if Ogg Vorbis playback fails to initialize as shown in #33, meaning that XAudio2 is missing. This part of the load process should be handled separately instead of by the global error handler, so that players can get clear instructions on how to fix the problem.

**Comment by blindpilot** [comment]
Hello to you Munawar, from Ron Kolesar. 
1. You gave me a link to grab the following. 
Three-D-Velocity-Binaries-master.zip
2 So, I went to 7 zip and extracted that zip file and received the following new folder. 
Three-D-Velocity-2.10
So what do I do with this file and what is the next steps to gain access to the TDV.exe file to extract it to the 
C:\program files (X86)\bpc games\3 d Velocity folder?
Many Thanks. 
Ron

**Comment by blindpilot** [comment]
Well, 
1. I down loaded the link that you’ve given to me which is 
Three-D-Velocity-Binaries-master.zip
2. I tapped my applications key and down arrowed down to 7 zip and smacked enter
3. down arrowed to extract files and they went into the down load folder and that folder is as follows:
Three-D-Velocity-2.10
So what do I do next?
Hope that answers your questions because that’s exactly what I did. 
I miss the good old days when we went to the BSC programs web site, went to our account and simply down loaded the next folder and or exe file. 
We removed what we had and simply like any other program, we’d simply install it. 
Now my question for you and the group. 
I was told that a x-box 360 controller 
1. could be plugged into a PC’s USB port.
2. Would they have the two sticks on them?
The left of course to control the pitch and roll and the right to control the velocity and banking features.
Now if we only could find something since jumping from the older 32 bit processors that gave us the force feedback feature to the 64 bit processor that we sadly can’t find a USB hand held unit with two sticks that would work not only in the 64 bit processor but also regain the force feedback feature as well. 
The TDV program, is the only hand to ear project that I’ve still seen that has force feedback. 
I know that the Blast chamber would be awesome if we had a unit that supported not only force but shock feedback as well. 
Just some thoughts And I hope I’ve given you some thing to help me to install TDV as well. 
Many Thanks. 
Ron AKA The Blind Pilot and in the real world, 
KR3DOG-PA-WCECTM

**Comment by munawarb** [comment]
Hi @blindpilot, I'm not sure what to tell you. I just now downloaded the binaries and extracted them using 7-Zip, and it resulted in a folder called `Three-D-Velocity-Binaries-master`. I went into that folder to find another folder called `Three-D-Velocity-Binaries-master`. Going into that one, I see all the files to run TDV. I have no idea where this tdv-2.10 folder is coming from on your system.

**Comment by blindpilot** [comment]
Hi Munawar. 
I don’t know what happened as well. 
But I just did what you did and finally found the main folder of 
Three-D-Velocity-Binaries-master
Smacked enter on it and the sub folder of 
Three-D-Velocity-Binaries-master
Finally showed up. 
Now, how do I get all of those files into the folder that I have at the following path?
C:\program files (x86)\BPC Games\3 D Velocity?
Do I select all of the files after going into the 
Three-D-Velocity-Binaries-master folder and just copy them out to the folder that I have shown way down below in this letter.
Or do I attempt to extract the  files within the 
Three-D-Velocity-Binaries-master
folder by only high lighting the
Three-D-Velocity-Binaries-master
folder, and go down to 7 zip and attempt to extract the files to the 
C:\program files (x86)/BPC Games\3 D Velocity folder?
Just trying to figure which way I should go so that I can get TDV to work once again.
A huge thanks for at least a step in the correct direction. 
Ron

**Comment by blindpilot** [comment]
Hi Munawar. 
Just thought you’d like to know that it finally worked out. 
I too went where you went and I also finally saw the files. 
I simply selected all of the files and copied them all to the folder that I wanted them to go in and the tdv.exe file fired right up for me. 
Sorry to be such a pain in the neck. 
Even though you probably could think of other places I might be a pain in. SMILES. 
Now, can I ask the one question once again. 
Would a X-Box 360 handheld unit 
1. work out for us, to be plugged into a PC’s USB port? 
2. come with two sticks for flight simulators?
3. do you think the X-Box 360 handheld controllers would have force feedback and also shock feedback for the pipe version two known as Blast Chamber since you’re dealing with pipes that not only has ice cold water but live electricity running through them as well. 
I think have force feedback and shock feedback would bring the hand to ear programs closer to the real thing and send chills down the player’s backbone. SMILES. 
I applaud you for thinking up a hand to ear program that has at least force feedback written into the flight simulator. 
You can correct me if I’m wrong. 
But if I recall, TDV is the only hand to ear program for the blind gamer that has force feedback written into the program. 
This is a huge shame. 
To bad none of the other hand to ear designers asked if you’d be willing for a small fee to share your force feedback technology. 
A huge thanks for all of your help. 
Ron U.S. ham station KR3DOG-PA-WCECTM
Pennsylvania West County Emergency Com-Tree Manager.
