### ISSUE TITLE
All fighters are numbered 1 on mission mode

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#6]
I have noticed that all fighters are numbered 1 in mission mode, even when there are multiple of them at the same time. It's confusing when you chase the closest  fighter, leave it, lock onto closest fighter number1 and see that it went to another direction.

**Comment by munawarb** [comment]
@burakyuksek I can't reproduce this one. In Mission Mode, when you're attacked by fighters, the game will randomly assign them numbers 1 through 6. This is because all the sounds are recorded, and there are only fighters 1 through 6 available. So yes, if there is a fighter1, and another fighter comes, chances are good that they will also be tracked as fighter1 on your radar. This isn't a bug; it's part of the design, and limitations of recorded sound files to read out information. :)

As far as locking is concerned, keep in mind that the lock menu is always ordered with the closest threat at the top of the list. So if you want to engage a fighter who is closer, simply untrack the last fighter you had a track on and lock onto the first fighter in the menu.
