### ISSUE TITLE
Proposal for a key to speak throttle position as a percentage

### ISSUE THREAD

**Issue by thomas-t-w** [munawarb/Three-D-Velocity#86]
Suppose I am going full throttle. I then hold the down arrow key for a few seconds and my engine RPMs start decreasing. I have no way of determining the percentage of the throttle until the engine rpms stop decreasing. If I breaked, this would also allow me to get an idea of what my rpms would increase to after I released the break without adjusting the throttle. On a flite controller, this can be achieved by actually feeling the mechanical position of the throttle.

**Comment by blindpilot** [comment]
I deeply agree with you on that wonderful recommendation that you made.
Ron who’s looking for a Flight yoke and twistable throttle controller with enough buttons on it for all of TDV’s features and to use it with other Hand to Ear programs and hopefully with a new civilian flight simulator that we’re trying to make blind friendly as well.
It would be nice for force feedback for the two stick hand controller, and any recommendations for a set of Ruther kettles also hopefully with force feedback to be able to feel the bumps and ground also would be nice to be able to feel when you start to leave the ground and when your tail hook and or landing gear touches the tarmac for a runway.
Many thanks. 
Ron who grounded right now.

From: thomas-t-w 
Sent: Saturday, June 8, 2019 00:59
To: munawarb/Three-D-Velocity 
Cc: Subscribed 
Subject: [munawarb/Three-D-Velocity] Proposal for a key to speak throttle position as a percentage (#86)

Suppose I am going full throttle. I then hold the down arrow key for a few seconds and my engine RPMs start decreasing. I have no way of determining the percentage of the throttle until the engine rpms stop decreasing. If I breaked, this would also allow me to get an idea of what my rpms would increase to after I released the break without adjusting the throttle. On a flite controller, this can be achieved by actually feeling the mechanical position of the throttle.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

In the good old days of Morse code Shorthand, 73's AKA Best Regards and or Best Whishes,
From Ron U.S. Ham Radio Station KR3DOG-PA-WCECTM
Pennsylvania West County Emergency Com-Tree Manager

**Comment by munawarb** [comment]
Hi,
This is a great suggestion. What are your thoughts on having the game automatically announce the throttle position as you change it? I think TDV already has enough keys to remember.

**Comment by blindpilot** [comment]
I agree with you on that point Munawar.
I like the throttle position feature to automatically tell you what your velocity is at.
Because like yourself, I agree with your point, there are quite a bit to memorize.
Did you see my one letter to you?
I was trying to bounce a duel stick handheld device off of you.
Just was curious to know if you found a two stick hand i with or without force feedback whith enough buttons on the unit to completely take over all of TDV’s features via the duel stick hand controller.
In my opinion, it’s easier and its also more fun to fly TDV via a duel stick handheld device and to press the buttons for the guns and what have you instead of using the keyboard.
Just was curious if you found anything with or without force feedback for a recommendation for me to find a yoke and twistable thruttle controller to get back in the air once again?
I would prefer something that would support TDV’s force feedback feature.
and there’s a roomer that TDV will work with USB rutter petals. IS this true for closer to realistic flight?
I still say that the force feedback feature was a huge selling point of the TDV program back in the good old days of the 32 bit processors.
It’s a huge shame that:
1. We never could find a two stick unit that would support the force feack in the newer faster 64 bit processor world.
2. Its also sad that from what I’ve seen, TDV is the only hand to ear pr
uct with force feedback written into the program.
I’m surprised that none of the other hand to ear companys haven’t contacted you and for a fee to have you share your force feedback technology.
I love and it works with win 10 Pipe version two, better known as the old Blast Chamber game.
Force feedback would be awesome for that game, also shock feedback also would be great fo that game as well.
Because some of the sewer pipes that you’re fixing have live electricity running through them, and if you’re not careful, you’ll get fried. SMILES.
Now have the player feel that at a safe level or fall down one of the manholes with force feedback.
\\\\\\\\I think if dropping down through one of the manhole covers with force feedback would make a player to check their shorts to make sure there’s no surprises in their shorts. SMILES.
I’m glad you wrote me back.
Its been a long time since the two of us has talked.
We had a good project that we wer beta testing back starting in 2010.
I still say you have one hell of a product for today as well.
I don’t say that to lightly or give recommendations to easily as well.
I have to thoroughly play with a product for a few days before I give a recommendation or suggested it to someone.
I’ve been trying to get in touch with the people behind the Microsoft Flight Simulator 2020 project.
Do a surch on face book or on the internet and you’ll be able to read all about the bombshell that Microsoft dropped on all of us this year.
Here we all thought Microsoft was just sitting on their fannies for the passed seven years.
But they’re going to build a hole new flight simulator from scratch from the ground up.
I have a letter that I’ve worked on for about the last three to five days on about:
1. How a blind person interacts with

**Comment by blindpilot** [comment]
I agree with you on that point Munawar.
I like the throttle position feature to automatically tell you what your velocity is at.
Because like yourself, I agree with your point, there are quite a bit to memorize.
Did you see my one letter to you?
I was trying to bounce a duel stick handheld device off of you.
Just was curious to know if you found a two stick hand controller with or without force feedback whith enough buttons on the unit to completely take over all of TDV’s features via the duel stick hand controller.
In my opinion, it’s easier and its also more fun to fly TDV via a duel stick handheld device and to press the buttons for the guns and what have you instead of using the keyboard.
Just was curious if you found anything with or without force feedback for a recommendation for me to find a yoke and twistable thruttle controller to get back in the air once again?
I would prefer something that would support TDV’s force feedback feature.
and there’s a roomer that TDV will work with USB rutter petals. IS this true for closer to realistic flight?
I still say that the force feedback feature was a huge selling point of the TDV program back in the good old days of the 32 bit processors.
It’s a huge shame that:
1. We never could find a two stick unit that would support the force feadback in the newer faster 64 bit processor world.
2. Its also sad that from what I’ve seen, TDV is the only hand to ear program with force feedback written into the program.
I’m surprised that none of the other hand to ear companys haven’t contacted you and for a fee to have you share your force feedback technology.
I love and it works with win 10 Pipe version two, better known as the old Blast Chamber game.
Force feedback would be awesome for that game, also electrical shock feedback also would be great for that game as well.
Because some of the sewer pipes that you’re fixing have live electricity running through them, and if you’re not careful, you’ll get fried. SMILES.
Now have the player feel that at a safe level or fall down one of the manholes with force feedback.
\\\\\\\\I think if dropping down through one of the manhole covers with force feedback would make a player to check their shorts to make sure there’s no surprises in their shorts. SMILES.
I’m glad you wrote me back.
Its been a long time since the two of us has talked.
We had a good project that we wer beta testing back starting in 2010.
I still say you have one hell of a product for today as well.
I don’t say that to lightly or give recommendations to easily as well.
I have to thoroughly play with a product for a few days before I give a recommendation or suggested it to someone.
I’ve been trying to get in touch with the people behind the Microsoft Flight Simulator 2020 project.
Do a surch on face book or on the internet and you’ll be able to read all about the bombshell that Microsoft dropped on all of us this year.
Here we all thought Microsoft was just sitting on their fannies for the passed seven years.
But they’re going to build a hole new flight simulator from scratch from the ground up for 2020.
The only thing I know is the release date is scheduled for October 13th, 2020.
I have a letter that I’ve worked on for about the last three to five days on about:
1. How a blind person interacts with their pc.
2. The different screen readers that are out there.
3. What I think would make the Microsoft Flight simulator 2020 project as close to the real world but also still blind friendly so that we too can continue to enjoy the product.
4. The additional programs that we ended up picking up to make FSX or now simply FS 2020 as close to the real world as possible and also for the blind that it’s still enjoying to get in the aircraft and take off with.
I’m trying to find a e-mail address to write to or a phone number here in the states to call and try to get a e-mail to ship my letter as a beta tester to ship to them so that the BVI Pilot isn’t left out of the fs 2020 project.
Been cool that you wrote to me and we had this time to chat.
Can’t wait to see your recommendations on my letter.
Ron AKA The Blind Pilot

**Comment by munawarb** [comment]
Hi @blindpilot,
I'm no longer as invested in this project as I used to be when it was commercial, so I'm hardly the person to ask about new developments in hardware for flight simulators which is probably why you haven't gotten a satisfactory response. Your best bet is to ask around on places where there are active gamers instead of repeatedly derailing issue threads concerning TDV. Try [the Audiogames forum](http://forum.audiogames.net). I'm sure no one who's watching the TDV repo appreciates these long-winded messages that completely take issues off-topic, especially the issues' authors (I've seen you derail other issues on this repo too.) Kindly create new issues for off-topic messages and don't hijack other issues. Remember: Github is NOT a mailing list so let's keep the discussions appropriate to the respective thread.

Finally, please remember that all messages you post on Github are public. I've warned you about this long time ago in another issue where you posted your personal medical problems.

Re: the letter you speak of: I don't recall any personal messages from you, but you're welcomed to contact me offline if you want to.

**Comment by thomas-t-w** [comment]
Hi Munawar
I have thought about this a lot today. I like the idea of speaking throttle position, however, I think we would want to ensure that the announcement of messages doesn't get behind the actual throttle position if the user holds down the up or down arrow keys. One thing I thought of is is ascending beeps at 25, 50, 75, and 100 with maybe announcements of throttle position when the keys were actually released. Maybe we just use beeps but have them at closer increments. One thing I worry about and want to avoid is too much speech slowing down gameplay.

**Comment by munawarb** [comment]
Hi,
This particular announcement will be a sync so it won't pause the game. But I like your idea of a tone indicator better than announcements. The game already gives a lot of verbal feedback. Do you have a wave file of an indicator sound you'd like to use?

**Comment by thomas-t-w** [comment]
I don't have any preference. There are so many sounds already in the game and I wonder if one could be reused. How about the click when moving between menu options as an example.

**Comment by munawarb** [comment]
Yes, that could definitely work.

**Comment by munawarb** [comment]
The sound for movement through menus probably won't work here. It sounds too close to the lock alert sound and might confuse other players. I'll leave this open until I can get a proper sound from someone. Do you have any suggestions for alternate sounds that are already in the game?

**Comment by burakyuksek** [comment]
Hello,
Would this do the job?
https://we.tl/t-R7AMpBgis4

**Comment by munawarb** [comment]
Perfect. Thanks! I found a sound for it already but I think I'll use this one instead.
